### ISSUE TITLE
How to deploy it

### ISSUE THREAD

**Issue by 95zz** [chris-visser/meteor-vue-admin#10]
How to deploy it

**Comment by chris-visser** [comment]
Depending on your cloud, you can simply build it into a plain node.js app. In your root run:

```
npm run build
```

This will create a bundle folder with a plain nodejs app. Set the ROOT_URL to the url of your site and set the MONGO_URL variable that links to your mongo database and that's it. You can simply follow the Meteor guide on deployment:

https://guide.meteor.com/deployment.html

**Comment by 95zz** [comment]
thank you
