### ISSUE TITLE
Excuse me, Why you don't use `imports/` structure?

### ISSUE THREAD

**Issue by thearabbit** [chris-visser/meteor-vue-admin#7]
Excuse me, Why you don't use `imports/` structure?

**Comment by chris-visser** [comment]
The imports structure is considered deprecated in Meteor. Besides that, i'm trying to follow node standards as much as possible.

**Comment by thearabbit** [comment]
thanks, so it mean that all of file is auto load.

**Comment by chris-visser** [comment]
The main reason I like the switch if because it becomes much better to understand what things get loaded where. That was one of the main reasons for Meteor do do that switch aswell :)
