### ISSUE TITLE
How to use `keep-alive router` with Tab style?

### ISSUE THREAD

**Issue by thearabbit** [chris-visser/meteor-vue-admin#8]
I would like to manage `keep-alive router` with Tab style.

![image](https://user-images.githubusercontent.com/4495160/50510927-20b04e00-0abe-11e9-8526-ed75c8e1c18a.png)
  
Could example?

**Comment by chris-visser** [comment]
The admin is just using a plain vue-router. You can find examples on how to use keep-alive here:

https://vuejs.org/v2/guide/components-dynamic-async.html

**Comment by thearabbit** [comment]
Very thanks for your reply.
