### ISSUE TITLE
Problem with big data on Select Opts?

### ISSUE THREAD

**Issue by thearabbit** [chris-visser/meteor-vue-admin#9]
`My Restaurant Project`, I used `Meteor + Element UI`.
It have problem on the big data on `Select Opts > 10000 records` in Sale form (Dynamic input).
I tried to use `Remote Select`, but still have many problem on `Edit Form` or Sale many product (slow).
![image](https://user-images.githubusercontent.com/4495160/50531480-3c0e6e00-0b3d-11e9-83ad-00f8a82cc682.png)

And now I try the new project (POS) on `Meteor + Vuetify`, but still the same problem.
Could you advice/share, how to solve?

**Comment by chris-visser** [comment]
Sorry, but this question could better be asked on the [Meteor Forum](https://forums.meteor.com/)

**Comment by thearabbit** [comment]
Sorry, I miss to confirm you, Now It work fine for Popup Editable.
Use normal table list view, and show form object when I clicked any row
🥇
